import type { NextPage, GetServerSideProps, InferGetServerSidePropsType } from 'next'
import React, {useState} from 'react'
import Head from 'next/head'
import Image from 'next/image'
import Card from '../components/Card'
import Modal from '../components/Modal'
import MoreInfo from '../components/MoreInfo'
import {getMovies, getMovieById} from '../api/getMovies'
import { Movie, FullMovieInfo } from '../types';
import styles from '../styles/Home.module.css'

type Props = {
  movies: Movie[]|null
}

const initialFullMovieState: FullMovieInfo = {
  description: '',
  duration: 0,
  genres: [],
  id: '',
  moods: [],
  releaseDate: '',
  releaseYear: 0,
  title: '',
  topCast: []
}

const Home: NextPage<Props> = ({movies}) => {
  const [isActive, setIsActive] = useState<boolean>(false);
  const [currentMovie, setCurrentMovie] = useState<FullMovieInfo>(initialFullMovieState);

  const handleClick = async (
		e: React.MouseEvent<HTMLDivElement>
  ): Promise<void> => {
		const { id } = e.currentTarget.dataset;
		const movie = await getMovieById(id);
		movie ? setCurrentMovie(movie) : setCurrentMovie(initialFullMovieState)
    setIsActive(true)
  };

  return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={styles.main}>
				<h1 className={styles.title}>
					Welcome to <a href="https://nextjs.org">Next.js!</a>
				</h1>

				<p className={styles.description}>
					Get started by editing{' '}
					<code className={styles.code}>pages/index.tsx</code>
				</p>

				<div className={styles.grid}>
					{movies &&
						movies.map((movie) => (
							<Card
								key={movie.id}
								movie={movie}
								handleClick={handleClick}
							/>
						))}
				</div>
				<Modal isActive={isActive} setIsActive={setIsActive}>
					<MoreInfo currentMovie={currentMovie} />
				</Modal>
			</main>

			<footer className={styles.footer}>
				<a
					href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
					target="_blank"
					rel="noopener noreferrer"
				>
					Powered by{' '}
					<span className={styles.logo}>
						<Image
							src="/vercel.svg"
							alt="Vercel Logo"
							width={72}
							height={16}
						/>
					</span>
				</a>
			</footer>
		</div>
  );
}

export const getServerSideProps: GetServerSideProps = async (context) => {
	const movies = await getMovies()
  return {
    props: {
      movies
    }
  }
};

export default Home
